global:
  scrape_interval: 15s

scrape_configs:
  - job_name: "prometheus"
    static_configs:
      - targets: ["prometheus:9090"]
  - job_name: "node-exporter"
    static_configs:
      - targets: ["node-exporter:9100"]
  - job_name: "cadvisor"
    static_configs:
      - targets: ["cadvisor:8098"]
  - job_name: "celery-flower"
    static_configs:
      - targets: ["celery-flower:5555"]
  - job_name: "statsd-exporter"
    static_configs:
      - targets: ["statsd-exporter:9102"]
